name: gofre-stack
version: "3.8"
services:
  auth:
    container_name: auth_microservice
    image: "auth-microservice"
    build:
      context: "./backend/services/auth"
      dockerfile: Dockerfile
    env_file:
      - backend.env
    networks:
      - gofre-network
    ports:
      - "8081:80"
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Gofre
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
    networks:
      - gofre-network
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: geuberlu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"
    networks:
      - gofre-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/data:/prometheus
    networks:
      - gofre-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
    networks:
      - gofre-network

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/config.yaml:/etc/loki/loki-config.yaml
    #   - ./docker/loki/data:/loki
    networks:
      - gofre-network
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./docker/loki/promtail-config.yml:/etc/promtail/promtail-config.yaml
    networks:
      - gofre-network
networks:
  gofre-network:
    driver: bridge
