
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  
  
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]

  # DIRETÓRIOS PARA IGNORAR
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]

  # DIRETÓRIOS PARA MONITORAR (AQUI ESTÁ O SEGREDO)
  include_dir = [".", "../../pkg"]

  exclude_file = []

  delay = 1000 # 1 segundo evita rebuilds excessivos se salvar rápido

 
  stop_on_error = true

  send_interrupt = false

  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true